### ISSUE TITLE
Want to contribute

### ISSUE THREAD

**Issue by Astha-Bhushan** [Darknez07/MachineLearningModels#1]
I am a beginner and I would like to contribute to this repo. Please guide me .

**Comment by Darknez07** [comment]
@Astha-Bhushan  What you want to do, know about machine learning?

**Comment by Astha-Bhushan** [comment]
I know clustering, regression, logistic, CNN and NLP model training evaluation and preprocessing

**Comment by Darknez07** [comment]
Sure than Show me a CNN code on the brain tumor dataset, do you know word embeddings in NLP

**Comment by Astha-Bhushan** [comment]
Okay. Yes, I know word embedding.

**Comment by Darknez07** [comment]
Good do u have any code i could look into

**Comment by Darknez07** [comment]
Cause this repo needs explanation for what you are doing

**Comment by Astha-Bhushan** [comment]
I have text summarization code, it does not have word embedding but you can look into that code.And I have done Kaggle cat vs dog, I can use that for the brain tumor dataset

**Comment by Darknez07** [comment]
@Astha-Bhushan  yea let's look at the code

**Comment by Darknez07** [comment]
@Astha-Bhushan You can show me text preprocessing in the repo

**Comment by Astha-Bhushan** [comment]
ya sure

**Comment by Astha-Bhushan** [comment]
please add hactober fest accepted label to it

**Comment by Darknez07** [comment]
ok sure wait a minute @Astha-Bhushan , if you can do the edit the readme with what did u do and explain a little and pull request is accepted so  can help beginners. I will merge it then.

**Comment by Astha-Bhushan** [comment]
okay

**Comment by Darknez07** [comment]
@Astha-Bhushan  this is closed now
