### ISSUE TITLE
Interested in contributing

### ISSUE THREAD

**Issue by arch-raven** [Darknez07/MachineLearningModels#6]
I am an Engineering Undergrad and Data Science Enthusiast. If you could point out any topic to continue in sequence, I would be glad to share my knowledge on it. I am looking to make some meaningful contributions to `hacktoberfest`.

**Comment by Darknez07** [comment]
Yea for data science probably start with this repo and as per contribution if you are familiar with basic concepts I am looking for more graphical or visualizations in the data
